apiVersion: apps/v1
kind: Deployment
metadata:
  name: me
spec:
  selector:
    matchLabels:
      app: me
  template:
    metadata:
      labels:
        app: me
    spec:
      initContainers:
        - name: me-migrate
          image: ghcr.io/xetera/me:latest
          imagePullPolicy: Always
          command:
            - npx
            - prisma
            - migrate
            - deploy
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: me-db-url
                  key: DATABASE_URL
      containers:
        - name: me
          image: ghcr.io/xetera/me:latest
          imagePullPolicy: Always
          resources:
            limits:
              memory: "128Mi"
              cpu: "100m"
          ports:
            - containerPort: 3000
          env:
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: "http://alloy.monitoring.svc.cluster.local:4318"
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: me-db-url
                  key: DATABASE_URL
          volumeMounts:
            - name: me-config
              mountPath: /app/config.toml
              subPath: config.toml
      volumes:
        - name: me-config
          secret:
            secretName: me-config
