---
- hosts: all
  roles:
    - role: dokku_bot.ansible_dokku
  vars:
    domains:
      - me.xetera.dev
    database_url: "file:../me.db"
    container_mount_path: "/store"
    tls_proxy_network: "tls-net"
    host_mount_path: "/var/lib/dokku/data/storage/{{ app }}"
  tasks:
    - name: Create app
      dokku_app:
        app: "{{ app }}"
    - name: Set to use caddy
      ansible.builtin.shell:
        # sadly there's no ansible command for this
        cmd: "dokku proxy:set {{ app }} caddy"
    - name: Setting domains
      dokku_domains:
        app: "{{ app }}"
        domains: "{{ domains }}"
    - name: Setting config
      dokku_config:
        app: "{{ app }}"
        config:
          DOKKU_APP_TYPE: dockerfile
          DATABASE_URL: "{{ database_url }}"
          CONFIG_PATH: "{{ container_mount_path }}/config.toml"
    - name: Create tls-proxy network
      dokku_network:
        name: "{{ tls_proxy_network }}"
    - name: Join tls-proxy network
      dokku_network_property:
        app: "{{ app }}"
        property: attach-post-create
        value: "{{ tls_proxy_network }}"
    - name: Copy configuration
      ansible.builtin.copy:
        src: config.toml.enc
        dest: "{{ host_mount_path }}/config.toml"
        remote_src: false
    - name: Setting storage
      dokku_storage:
        app: "{{ app }}"
        mounts:
          - "{{ host_mount_path }}:/data"
