apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: me-config
  namespace: default
spec:
  # this unfortunately has to be a secret instead of a configmap because it involves the auth token
  itemPath: "vaults/k8s-cloud/items/me-config"
---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: me-db-url
  namespace: default
spec:
  itemPath: "vaults/k8s-cloud/items/me-db-url"
